### ISSUE TITLE
train on multi-GPU

### ISSUE THREAD

**Issue by MartinYue** [zhihou7/FCL#1]
hi, thanks for your great job. I noticed that this project is mainly based on VCL(which based on iCAN). And in VCL projects issues you once said that have met some bugs when running on multi-GPU. Does FCL have the same bug?
thank you!

**Comment by zhihou7** [comment]
No. in VCL, I tried to compose samples among GPUs, i.e., each GPU has an image (model parallel). But on FCL, It is not necessary to compose samples among different GPUs. But, I guess when we run FCL on multi-GPU, we need to tune the hyperparameters (e.g. lr)

**Comment by MartinYue** [comment]
thanks for your reply. XD
